### ISSUE TITLE
DDLParserError: Unknown symbol '\\'

### ISSUE THREAD

**Issue by ivbeg** [xnuinside/simple-ddl-parser#143]
**Describe the bug**
Error DDLParserError: Unknown symbol '\\' happens on certain files

**To Reproduce**
1. Take file https://github.com/UGTU\UGTUKadrProject\blob\14ba90064feaf83b00a66b38500458d50d4337c8\Kadr\HRDatabase\dbo\Tables\OK_DopInf.sql 
2. Use code `ddl = parse_from_file(filepath)`
4. See error `DDLParserError: Unknown symbol '\\'`

**Expected behavior**
No error expected

Traceback attached
[traceback.txt](https://github.com/xnuinside/simple-ddl-parser/files/9027550/traceback.txt)

**Comment by xnuinside** [comment]
issue was fixed in version 0.28.0, now sql https://github.com/UGTU/UGTUKadrProject/blob/14ba90064feaf83b00a66b38500458d50d4337c8/Kadr/HRDatabase/dbo/Tables/OK_DopInf.sql is parsed validly and produces output.

I will close the issue - if will be something wrong feel free to open or create another one. Thank you!
