### ISSUE TITLE
SQLServer varchar with (max) not handled

### ISSUE THREAD

**Issue by ctimmer** [xnuinside/simple-ddl-parser#187]
**Describe the bug**
With this column declaration:
```sql
[object_def] [varchar](max) NULL,
```
the (max) is interpreted as '()'

**Expected behavior**
Would like to see it passed through as '(max)'

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 2023/01/12

**Comment by xnuinside** [comment]
@ctimmer , hi! this issue was  fixed in some of the latest versions, at least I have already for this test - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/dialects/test_mssql_specific.py#L138 and it is parsed validly on version 0.29.1. please try, if there is still issue - reopen it and provide a full example please. And thank you!
